;Proxy default, whitelist direct, for devices.
;Mind US*/UM flag changes and loops.
[custom]

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🇨🇳 谷歌中国,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,subweb.ccsub.site
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,zaobao.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,zaobao.com.sg
ruleset=🚀 节点选择,[]DOMAIN-KEYWORD,kemono
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,addons.mozilla.org
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,artifacts.bitwarden.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,c.mi.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,onedrive.live.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,store.steampowered.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,steamcommunity.com
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bing.list
ruleset=💵 PayPal,[]DOMAIN-SUFFIX,paypal.com
ruleset=💵 PayPal,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/PayPal.list
ruleset=💬 AI平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 AI平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=💬 AI平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Gemini.list
ruleset=💬 AI平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/EHGallery.list
ruleset=📺 油管服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📺 油管服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=📺 Emby服务,[]DOMAIN-SUFFIX,iflya321.com
ruleset=📺 Emby服务,https://raw.githubusercontent.com/jklolixxs/listes/master/Clash/Ruleset/PlusEmbyProxy.ini
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 TikTok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=🌐 国际媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🔍 谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🔍 谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🛤️ 类型匹配,[]IN-TYPE,SOCKS/HTTP/HTTPS
ruleset=🐟 其他漏鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT`.*
custom_proxy_group=💬 AI平台`select`[]🇺🇸 美国节点`[]🚀 节点选择`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇭🇰 香港节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT`.*
custom_proxy_group=🔍 谷歌服务`select`[]🇺🇸 美国节点`[]🚀 节点选择`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇭🇰 香港节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT`.*
custom_proxy_group=📺 油管服务`select`[]🇺🇸 美国节点`[]🚀 节点选择`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇭🇰 香港节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT`.*
custom_proxy_group=📺 Emby服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换`.*
custom_proxy_group=📺 TikTok`select`[]🇸🇬 狮城节点`[]🚀 节点选择`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇭🇰 香港节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT`.*
custom_proxy_group=📺 巴哈姆特`select`[]🧋 台湾节点`[]🇭🇰 香港节点`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT`[]🇭🇰 香港节点`[]🧋 台湾节点`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换
custom_proxy_group=🌐 国际媒体`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换
custom_proxy_group=💵 PayPal`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换
custom_proxy_group=🛤️ 类型匹配`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换`[]DIRECT
custom_proxy_group=🐟 其他漏鱼`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🧋 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]♻️ 自动选择`[]📌 手动切换
custom_proxy_group=🇨🇳 谷歌中国`select`[]DIRECT`[]🚀 节点选择`[]📌 手动切换`[]♻️ 自动选择
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]📌 手动切换`[]♻️ 自动选择
custom_proxy_group=🇭🇰 香港节点`select`[]♻️ 港 🇭🇰`(港|HK|hk|Hong Kong|HongKong|hongkong)
custom_proxy_group=🇺🇸 美国节点`select`[]♻️ 美 🇺🇸`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🧋 台湾节点`select`[]♻️ 台 🧋`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇸🇬 狮城节点`select`[]♻️ 新 🇸🇬`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇯🇵 日本节点`select`[]♻️ 日 🇯🇵`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
custom_proxy_group=🇰🇷 韩国节点`select`[]♻️ 韩 🇰🇷`(KR|Korea|KOR|首尔|韩|韓)
custom_proxy_group=📌 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://clients3.google.com/generate_204`300,5,100
custom_proxy_group=♻️ 港 🇭🇰`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://clients3.google.com/generate_204`300,5,100
custom_proxy_group=♻️ 美 🇺🇸`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://clients3.google.com/generate_204`300,5,100
custom_proxy_group=♻️ 台 🧋`url-test`(台|新北|彰化|TW|Taiwan)`http://clients3.google.com/generate_204`300,5,100
custom_proxy_group=♻️ 新 🇸🇬`url-test`(新加坡|坡|狮城|SG|Singapore)`http://clients3.google.com/generate_204`300,5,100
custom_proxy_group=♻️ 日 🇯🇵`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://clients3.google.com/generate_204`300,5,100
custom_proxy_group=♻️ 韩 🇰🇷`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://clients3.google.com/generate_204`300,5,100

enable_rule_generator=true
overwrite_original_rules=true
