# https://wiki.metacubex.one/example/geox
# https://wiki.metacubex.one/example/mrs
# https://github.com/MetaCubeX/meta-rules-dat
# https://github.com/Loyalsoldier/v2ray-rules-dat

proxy-providers:
  provider1:
    url: "订阅1链接"
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[provider1]"

  provider2:
    url: "订阅2链接"
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[provider2]"

proxies: 
  - name: US-CF
    server: 服务器
    port: 端口
    type: vmess
    uuid: UUID
    alterId: 0
    cipher: auto
    tls: true
    servername: 服务器
    network: ws
    ws-opts:
      path: /路径
      headers:
        Host: 服务器
    udp: true
  - name: "直连"
    type: direct
    udp: true

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.dat"
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country-lite.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

proxy-groups:

  - name: 节点选择
    type: select
    proxies: [香港,美国,台湾,新加坡,日本,韩国,其它地区,自动选择,手动切换,直连]

  - name: 哔哩哔哩
    type: select
    proxies: [直连,节点选择,香港,美国,台湾,新加坡,日本,韩国,其它地区,自动选择,手动切换]

  - name: 巴哈姆特
    type: select
    proxies: [台湾,香港,节点选择,美国,新加坡,日本,韩国,其它地区,自动选择,手动切换,直连]

  - name: 国际视听
    type: select
    proxies: [节点选择,香港,美国,台湾,新加坡,日本,韩国,其它地区,自动选择,手动切换,直连]

  - name: 谷歌服务
    type: select
    proxies: [节点选择,香港,美国,台湾,新加坡,日本,韩国,其它地区,自动选择,手动切换,直连]

  - name: 国内
    type: select
    proxies:  [直连,节点选择,香港,美国,台湾,新加坡,日本,韩国,其它地区,自动选择,手动切换]

  - name: 其他
    type: select
    proxies:  [直连,节点选择,香港,美国,台湾,新加坡,日本,韩国,其它地区,自动选择,手动切换]

  #分隔,下面是地区分组
  - name: 香港
    type: select
    proxies:  [香港自动]
    include-all: true
    exclude-type: direct
    filter: "(?i:\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]港)"

  - name: 美国
    type: select
    proxies:  [美国自动]
    include-all: true
    exclude-type: direct
    filter: "(?i:\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)"

  - name: 台湾
    type: select
    proxies:  [台湾自动]
    include-all: true
    exclude-type: direct
    filter: "(?i:\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b)"

  - name: 新加坡
    type: select
    proxies:  [新加坡自动]
    include-all: true
    exclude-type: direct
    filter: "(?i:\bSG[P]?\b|Singapore|新加坡|狮城|[^-]新)"

  - name: 日本
    type: select
    proxies:  [日本自动]
    include-all: true
    exclude-type: direct
    filter: "(?i:\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日)"

  - name: 韩国
    type: select
    proxies:  [韩国自动]
    include-all: true
    exclude-type: direct
    filter: "(?i:\bK[O]?R\b|Korea|首尔|韩|韓)"

  - name: 其它地区
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:🇺🇸|🇺🇲|\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇭🇰|\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]港|🇹🇼|\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b|🇸🇬|\bSG[P]?\b|Singapore|新加坡|狮城|[^-]新|🇯🇵|\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日|🇰🇷|\bK[O]?R\b|Korea|首尔|韩|韓)).*"

  - name: 手动切换
    type: select
    include-all: true
    exclude-type: direct

  - name: 自动选择
    type: url-test
    include-all: true
    exclude-type: direct
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100

  - name: 香港自动
    type: url-test
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100
    include-all: true
    exclude-type: direct
    filter: "(?i:\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]港)"

  - name: 美国自动
    type: url-test
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100
    include-all: true
    exclude-type: direct
    filter: "(?i:\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)"

  - name: 台湾自动
    type: url-test
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100
    include-all: true
    exclude-type: direct
    filter: "(?i:\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b)"

  - name: 新加坡自动
    type: url-test
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100
    include-all: true
    exclude-type: direct
    filter: "(?i:\bSG[P]?\b|Singapore|新加坡|狮城|[^-]新)"

  - name: 日本自动
    type: url-test
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100
    include-all: true
    exclude-type: direct
    filter: "(?i:\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日)"

  - name: 韩国自动
    type: url-test
    url: http://clients3.google.com/generate_204
    interval: 300
    tolerance: 100
    include-all: true
    exclude-type: direct
    filter: "(?i:\bK[O]?R\b|Korea|首尔|韩|韓)"

rules:
  - GEOIP,lan,DIRECT,no-resolve
  - RULE-SET,GoogleFCM,DIRECT
  - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,youtube,国际视听
  - GEOSITE,netflix,国际视听
  - GEOIP,netflix,国际视听
  - GEOSITE,spotify,国际视听
  - GEOSITE,google,谷歌服务
  - GEOIP,google,谷歌服务
  - GEOSITE,telegram,节点选择
  - GEOIP,telegram,节点选择
  - GEOSITE,gfw,节点选择
  - GEOSITE,CN,国内
  - GEOIP,CN,国内
  - GEOSITE,geolocation-!cn,其他
  - MATCH,其他

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
  GoogleFCM:
    <<: *domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/GoogleFCM.list"
